language: c
sudo: false

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
  # Add org channel
  - conda config --add channels ${ORGNAME}

script:
  # Create a test environment
  - conda create --yes -n test python=$python
  # Activate the test environment
  - source activate test
  # Add omnia dev channels
  - conda config --add channels https://conda.anaconda.org/omnia/label/dev
  # Install extras for OpenEye and testing
  - conda install --yes --quiet pip nose nose-timer
  # Build the recipe
  - conda build devtools/conda-recipe
  # Install the package
  - conda install --yes --use-local ${PACKAGENAME}-dev
  # Test the package
  - cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-timer -a '!slow' && cd ..
  # Test the examples
  - python benchmark/examples/baoab_vs_vvvr.py

os:
  - osx
  - linux

env:
  matrix:
    - python=2.7  CONDA_PY=2.7
    - python=3.4  CONDA_PY=3.4
    - python=3.5  CONDA_PY=3.5

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="benchmark"
